# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-23 18:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ConfluenceAPP', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='go',
            old_name='lat',
            new_name='mylat',
        ),
        migrations.RenameField(
            model_name='go',
            old_name='lon',
            new_name='mylong',
        ),
    ]
